service: my-worklog-function

frameworkVersion: ">=2.1.0 <3.0.0"

provider:
  name: aws
  region: ap-southeast-1
  runtime: ruby2.7

functions:
  my_worklog:
    handler: handler.user
    events:
      - http:
          path: user
          method: get